FROM zliea/alpine:3

ENV CONFIG_DIR=/etc/certsync

RUN apk add --no-cache ca-certificates \
 && update-ca-certificates \
 && rm -rf /var/cache/apk/* \
 && mkdir ${CONFIG_DIR}

ADD output/certsync-client /usr/local/bin
ADD docker/docker-entrypoint-client.sh /usr/local/bin/docker-entrypoint.sh

ENTRYPOINT ["docker-entrypoint.sh"]
CMD ["certsync-client"]
